/**
 * MIRROR — SOURCE OF TRUTH IS src/lib/identity.ts.
 *
 * Scripts under scripts/remediation/ cannot import TypeScript, and invariant
 * I-12 requires that the D-7 sign-in gate, every baseline writer and every
 * backfill share ONE eligibility predicate. This file is therefore a literal
 * behavioural mirror of src/lib/identity.ts.
 *
 * DO NOT EDIT THIS FILE ALONE. Change src/lib/identity.ts, mirror the change
 * here, and run:
 *
 *     node scripts/remediation/verify-identity-parity.mjs
 *
 * which compares both implementations over a shared fixture list (including
 * g.s_samuel@u.nus.edu — L-27) and exits 1 on any divergence. Drift here is
 * not cosmetic: a backfill keyed differently from the runtime writes rows no
 * session will ever match (I-1), and that failure is silent.
 *
 * PURE. No database, no env, no imports. Nothing in this file connects to
 * anything.
 */

/**
 * Anchored, ASCII-only. Each property is load-bearing:
 *   ^...$        rejects bob@u.nus.edu.evil.com
 *   single @     rejects bob@evil.com@u.nus.edu (the class excludes '@')
 *   '@' followed
 *   immediately
 *   by the domain rejects bob@sub.u.nus.edu
 *   [A-Z0-9._%-] ASCII only, so a Cyrillic-е homograph domain cannot match
 *   NO '+'       e1234567+x@u.nus.edu would canonicalise to a DIFFERENT key
 *                for the same human — a duplicate-account vector.
 *
 * `u.nus.edu` only: @nus.edu / @nus.edu.sg staff addresses are rejected (they
 * are the whole university, not Raffles Hall, and under D-1 admitting a domain
 * auto-grants hall booking rights). Staff go through AUTH_EMAIL_ALLOWLIST,
 * which confers sign-in and nothing else.
 */
const NUS_STUDENT_EMAIL = /^([A-Z0-9._%-]+)@U\.NUS\.EDU$/;

/** `.trim()` is load-bearing: auth.ts historically omitted it. */
export function normalizeEmail(email) {
  return (email ?? "").trim().toLowerCase();
}

export function isNusStudentEmail(email) {
  return NUS_STUDENT_EMAIL.test(normalizeEmail(email).toUpperCase());
}

/**
 * Returns "" for anything that is not a valid @u.nus.edu address, so
 * `canonicalUserID(e) !== ""` is exactly equivalent to `isNusStudentEmail(e)`.
 *
 * The localpart is NOT required to be E-format: `g.s_samuel@u.nus.edu` is a
 * real account here and canonicalises to "G.S_SAMUEL". Never gate eligibility
 * or the resident baseline on /^E\d{7}$/ (L-27).
 */
export function canonicalUserID(email) {
  const m = NUS_STUDENT_EMAIL.exec(normalizeEmail(email).toUpperCase());
  return m ? m[1] : "";
}

/**
 * POST-CANONICALIZATION SANITY CHECK. A pure SHAPE test carrying no
 * provenance — sound only over a string canonicalUserID() has just produced.
 * Backfills and merge scripts must call it as
 * `isCanonicalResidentID(canonicalUserID(user.email))`, never on a userID read
 * straight out of a document (I-8d).
 */
export function isCanonicalResidentID(userID) {
  return typeof userID === "string" && userID.length > 0 && !userID.includes("@");
}

/** @deprecated Alias — 05-verification.md §5 still names it this. */
export const isResidentEligible = isCanonicalResidentID;

export const AUTH_ERROR = { NOT_NUS_EMAIL: "NotNusEmail" };
