/**
 * MIRROR — SOURCE OF TRUTH IS src/lib/identity.ts.
 *
 * Scripts under scripts/remediation/ cannot import TypeScript, and invariant
 * I-12 requires that the D-7 sign-in gate, every baseline writer and every
 * backfill share ONE eligibility predicate. This file is therefore a literal
 * behavioural mirror of src/lib/identity.ts.
 *
 * DO NOT EDIT THIS FILE ALONE. Change src/lib/identity.ts, mirror the change
 * here, and run:
 *
 *     node scripts/remediation/verify-identity-parity.mjs
 *
 * which compares both implementations over a shared fixture list (including
 * g.s_samuel@u.nus.edu — L-27) and exits 1 on any divergence. Drift here is
 * not cosmetic: a backfill keyed differently from the runtime writes rows no
 * session will ever match (I-1), and that failure is silent.
 *
 * PURE. No database, no env, no imports. Nothing in this file connects to
 * anything.
 */

/**
 * Anchored, ASCII-only. Each property is load-bearing:
 *   ^...$        rejects bob@u.nus.edu.evil.com
 *   single @     rejects bob@evil.com@u.nus.edu (the class excludes '@')
 *   '@' followed
 *   immediately
 *   by the domain rejects bob@sub.u.nus.edu
 *   [A-Z0-9._%-] ASCII only, so a Cyrillic-е homograph domain cannot match
 *   NO '+'       e1234567+x@u.nus.edu would canonicalise to a DIFFERENT key
 *                for the same human — a duplicate-account vector.
 *
 * `u.nus.edu` only: @nus.edu / @nus.edu.sg staff addresses are rejected (they
 * are the whole university, not Raffles Hall, and under D-1 admitting a domain
 * auto-grants hall booking rights). Staff go through AUTH_EMAIL_ALLOWLIST,
 * which confers sign-in and nothing else.
 */
const NUS_STUDENT_EMAIL = /^([A-Z0-9._%-]+)@U\.NUS\.EDU$/;

/** `.trim()` is load-bearing: auth.ts historically omitted it. */
export function normalizeEmail(email) {
  return (email ?? "").trim().toLowerCase();
}

export function isNusStudentEmail(email) {
  return NUS_STUDENT_EMAIL.test(normalizeEmail(email).toUpperCase());
}

/**
 * Returns null for anything that is not a valid @u.nus.edu address, so
 * `canonicalUserID(e) !== null` is exactly equivalent to `isNusStudentEmail(e)`.
 *
 * C9 CHANGED THIS FROM "" TO null, mirroring src/lib/identity.ts. The absent
 * identity has left the `string` domain on purpose: "" is an in-band member of
 * the value domain that `where: {userID}`, `a === b`, `dict[k]` and
 * `k ?? fallback` all accept silently, and null is out-of-band.
 *
 * WHAT THAT COSTS ON THIS SIDE. The .ts half gets strictNullChecks to sweep
 * every consumer; .mjs gets NOTHING — no brand, no compiler, no `tsc --noEmit`.
 * So any test of the form `canonicalUserID(e) === ""` / `!== ""` in a script is
 * now VACUOUS rather than wrong-but-loud: `!== ""` is true for every input and
 * `=== ""` is true for none, which silently inverts eligibility checks and
 * disarms abort-on-empty-target gates. Prefer the falsy form (`!id`) or an
 * explicit `== null`; both survive either representation. Every such site in
 * scripts/ was swept when this landed — see the C9 comments in rbac-doctor.mjs,
 * rekey-canonical.mjs and inventory-rbac.mjs.
 *
 * RUNTIME BEHAVIOUR IS OTHERWISE UNCHANGED: both "" and null are falsy, so any
 * pre-existing `if (!userID)` guard keeps working identically. merge-accounts'
 * `nonEmpty()` already returned false for null, so its consumers were safe.
 *
 * The localpart is NOT required to be E-format: `g.s_samuel@u.nus.edu` is a
 * real account here and canonicalises to "G.S_SAMUEL". Never gate eligibility
 * or the resident baseline on /^E\d{7}$/ (L-27).
 */
export function canonicalUserID(email) {
  const m = NUS_STUDENT_EMAIL.exec(normalizeEmail(email).toUpperCase());
  return m ? m[1] : null;
}

/**
 * POST-CANONICALIZATION SANITY CHECK. A pure SHAPE test carrying no
 * provenance — sound only over a string canonicalUserID() has just produced.
 * Backfills and merge scripts must call it as
 * `isCanonicalResidentID(canonicalUserID(user.email))`, never on a userID read
 * straight out of a document (I-8d).
 */
export function isCanonicalResidentID(userID) {
  return typeof userID === "string" && userID.length > 0 && !userID.includes("@");
}

/**
 * C9. The ONE checked entry point for an id READ BACK FROM STORAGE rather than
 * derived here — e.g. a `UserRole.userID` straight out of Mongo.
 *
 * WHY THIS EXISTS IN THE .mjs AT ALL. The obvious argument against mirroring it
 * is that the TS version's whole point is the CanonicalUserID brand, and brands
 * are erased at runtime, so a plain-JS copy "means nothing". That argument is
 * half right and lands on the wrong conclusion. The function does two things:
 * it brands (compile-time, TS-only, genuinely meaningless here) and it RETURNS
 * null FOR ANYTHING FAILING THE SHAPE TEST, INCLUDING "" (runtime, and the
 * load-bearing half). A ""-keyed UserRole row — the I-8d red line — must enter
 * a migration script as ABSENT rather than as a usable key, and that hazard is
 * strictly WORSE in .mjs, where no type system is watching. rbac-doctor.mjs:115
 * already hand-rolls this exact shape test on a stored userID; this is the
 * shared name for it.
 *
 * So the export-surface mismatch is resolved by IMPLEMENTING, not by exempting.
 * Exempting would have meant teaching verify-identity-parity.mjs a per-symbol
 * allowlist — a hole in the one check that catches a function existing on one
 * side and not the other, punched open for a symbol that turns out to have real
 * runtime behaviour worth mirroring. Implementing keeps the surface check
 * absolute and costs eight lines.
 *
 * Carries NO provenance evidence — read isCanonicalResidentID's note. Never use
 * it to launder a caller-supplied id into a key.
 */
export function asStoredCanonicalUserID(id) {
  return isCanonicalResidentID(id) ? id : null;
}

/** @deprecated Alias — 05-verification.md §5 still names it this. */
export const isResidentEligible = isCanonicalResidentID;

export const AUTH_ERROR = { NOT_NUS_EMAIL: "NotNusEmail" };
