/**
 * MIRROR — SOURCE OF TRUTH IS src/lib/identity.ts.
 *
 * Scripts under scripts/remediation/ cannot import TypeScript, and invariant
 * I-12 requires that the D-7 sign-in gate, every baseline writer and every
 * backfill share ONE eligibility predicate. This file is therefore a literal
 * behavioural mirror of src/lib/identity.ts.
 *
 * DO NOT EDIT THIS FILE ALONE. Change src/lib/identity.ts, mirror the change
 * here, and run:
 *
 *     node scripts/remediation/verify-identity-parity.mjs
 *
 * which compares both implementations over a shared fixture list (including
 * g.s_samuel@u.nus.edu — L-27) and exits 1 on any divergence. Drift here is
 * not cosmetic: a backfill keyed differently from the runtime writes rows no
 * session will ever match (I-1), and that failure is silent.
 *
 * PURE. No database, no env, no imports. Nothing in this file connects to
 * anything.
 */

/**
 * Anchored, ASCII-only. Each property is load-bearing:
 *   ^...$        rejects bob@u.nus.edu.evil.com
 *   single @     rejects bob@evil.com@u.nus.edu (the class excludes '@')
 *   '@' followed
 *   immediately
 *   by the domain rejects bob@sub.u.nus.edu
 *   [A-Z0-9._%-] ASCII only, so a Cyrillic-е homograph domain cannot match
 *   NO '+'       e1234567+x@u.nus.edu would canonicalise to a DIFFERENT key
 *                for the same human — a duplicate-account vector.
 *
 * `u.nus.edu` only: @nus.edu / @nus.edu.sg staff addresses are rejected (they
 * are the whole university, not Raffles Hall, and under D-1 admitting a domain
 * auto-grants hall booking rights). Staff go through AUTH_EMAIL_ALLOWLIST,
 * which confers sign-in and nothing else.
 */
const NUS_STUDENT_EMAIL = /^([A-Z0-9._%-]+)@U\.NUS\.EDU$/;

/** `.trim()` is load-bearing: auth.ts historically omitted it. */
export function normalizeEmail(email) {
  return (email ?? "").trim().toLowerCase();
}

export function isNusStudentEmail(email) {
  return NUS_STUDENT_EMAIL.test(normalizeEmail(email).toUpperCase());
}

/**
 * Returns null for anything that is not a valid @u.nus.edu address, so
 * `canonicalUserID(e) !== null` is exactly equivalent to `isNusStudentEmail(e)`.
 *
 * C9 CHANGED THIS FROM "" TO null, mirroring src/lib/identity.ts. The absent
 * identity has left the `string` domain on purpose: "" is an in-band member of
 * the value domain that `where: {userID}`, `a === b`, `dict[k]` and
 * `k ?? fallback` all accept silently, and null is out-of-band.
 *
 * WHAT THAT COSTS ON THIS SIDE. The .ts half gets strictNullChecks to sweep
 * every consumer; .mjs gets NOTHING — no brand, no compiler, no `tsc --noEmit`.
 * So any test of the form `canonicalUserID(e) === ""` / `!== ""` in a script is
 * now VACUOUS rather than wrong-but-loud: `!== ""` is true for every input and
 * `=== ""` is true for none, which silently inverts eligibility checks and
 * disarms abort-on-empty-target gates. Prefer the falsy form (`!id`) or an
 * explicit `== null`; both survive either representation. Every such site in
 * scripts/ was swept when this landed — see the C9 comments in rbac-doctor.mjs,
 * rekey-canonical.mjs and inventory-rbac.mjs.
 *
 * RUNTIME BEHAVIOUR IS OTHERWISE UNCHANGED: both "" and null are falsy, so any
 * pre-existing `if (!userID)` guard keeps working identically. merge-accounts'
 * `nonEmpty()` already returned false for null, so its consumers were safe.
 *
 * The localpart is NOT required to be E-format: `g.s_samuel@u.nus.edu` is a
 * real account here and canonicalises to "G.S_SAMUEL". Never gate eligibility
 * or the resident baseline on /^E\d{7}$/ (L-27).
 */
export function canonicalUserID(email) {
  const m = NUS_STUDENT_EMAIL.exec(normalizeEmail(email).toUpperCase());
  return m ? m[1] : null;
}

/**
 * A BARE NUSNET ID AS A HUMAN TYPES IT — `E1234567`, but also `MARCUS-CHUA` —
 * back to the canonical key. Mirrors src/lib/identity.ts; read the long note
 * there for why it reconstructs the address instead of testing a shape.
 *
 * Two properties the parity gate asserts rather than assumes: the value set is
 * a SUBSET of canonicalUserID's (so M1 holds — `EXT:FOO` returns null because
 * ':' is outside NUS_STUDENT_EMAIL's capture class), and it proves NOTHING
 * about an account. It is a spelling conversion. `canonicalFromNusnetID("ASDF")`
 * is `"ASDF"`, and a caller that grants on that without first establishing a
 * live row has written a key no session will ever match (I-1).
 *
 * MIRRORED HERE BECAUSE THE SCRIPTS TAKE TYPED IDS. A remediation script given
 * a NUSNET id on argv has exactly this conversion to do, and the alternative is
 * the private derivation the ban in verify-identity-parity.mjs exists to stop.
 */
export function canonicalFromNusnetID(raw) {
  const s = (raw ?? "").trim();
  if (!s || s.includes("@")) return null;
  return canonicalUserID(`${s}@u.nus.edu`);
}

/**
 * THE EXTERNAL IDENTITY NAMESPACE. An admin-pinned key for a principal that has
 * no @u.nus.edu address — hall office staff, whose addresses are @nus.edu.sg
 * (08-userid-keydrift.md §3 Branch C). One `AuthAllowlist` row pins one address
 * to one of these.
 *
 * THE ':' IS THE WHOLE MECHANISM (M1). NUS_STUDENT_EMAIL's capture class is
 * `[A-Z0-9._%-]` — it does not contain ':' — so `canonicalUserID()` can NEVER
 * return a string matching this pattern, for ANY input, because every character
 * it can return comes from that class. The two key spaces are PROVABLY
 * DISJOINT, not conventionally separate.
 *
 * That is what makes the attack in 05-verification.md §164 —
 * `{ email: "attacker@gmail.com", pinnedUserID: "E1633673" }`, which would
 * hand an admin's authorization key to a stranger with NO grant path and
 * therefore NO escalation guard firing — UNREPRESENTABLE rather than merely
 * refused. `isExtUserID("E1633673")` is false, and the parity gate asserts it.
 *
 * Uppercase and `_` only, so a pin is legible in `RoleAuditLog.actorUserID` and
 * greppable across collections. Length-bounded at both ends: the 3-char floor
 * keeps `EXT:` alone from being a key, and the 32-char ceiling stops an id
 * being used to smuggle a payload into an audit row.
 *
 * WHY THIS IS MIRRORED INTO THE .mjs AT ALL, when the TS half's value is the
 * brand and brands are erased: same answer as asStoredCanonicalUserID below.
 * The runtime half — "return the absent value for anything failing the shape
 * test" — is the load-bearing half, and it is the half the scripts need.
 * provision-ext-account.mjs must refuse a pin outside this namespace, and
 * rbac-doctor.mjs must be able to REPORT a stored pin that is outside it (that
 * is a row which mints no identity at all — see M2 in
 * src/server/api/services/authAllowlist.ts). Both would otherwise hand-roll the
 * regex, which verify-identity-parity.mjs's private-derivation ban exists to
 * stop.
 */
export const EXT_ID = /^EXT:[A-Z0-9_]{3,32}$/;

/** Pure shape test over the EXT namespace. See EXT_ID for why ':' matters. */
export function isExtUserID(id) {
  return typeof id === "string" && EXT_ID.test(id);
}

/**
 * The ONE minting function for the EXT half of the brand — the exact mirror of
 * asStoredCanonicalUserID for the canonical half, and A RUNTIME CHECK, NEVER A
 * CAST. Every EXT id in this codebase passes through here.
 *
 * On the .ts side it is what pinnedUserIDFor calls on the value it READ BACK
 * OUT OF MONGO (mechanism M2), so a row typed by hand in Atlas mints NO
 * IDENTITY AT ALL rather than a bad one. On this side it is the same refusal,
 * available to scripts that have no type system watching them.
 */
export function asExtUserID(id) {
  return isExtUserID(id) ? id : null;
}

/**
 * POST-CANONICALIZATION SANITY CHECK. A pure SHAPE test carrying no
 * provenance — sound only over a string canonicalUserID() has just produced.
 * Backfills and merge scripts must call it as
 * `isCanonicalResidentID(canonicalUserID(user.email))`, never on a userID read
 * straight out of a document (I-8d).
 *
 * AN `EXT:` PIN PASSES THIS TEST — a documented false positive, asserted as
 * such by the parity gate. Safe only because every baseline writer takes an
 * EMAIL and canonicalizes internally (I-8d), so ensureBaseline returns false at
 * its `!userID` clause long before this predicate is consulted. See the fuller
 * note in src/lib/identity.ts.
 */
export function isCanonicalResidentID(userID) {
  return typeof userID === "string" && userID.length > 0 && !userID.includes("@");
}

/**
 * C9. The ONE checked entry point for an id READ BACK FROM STORAGE rather than
 * derived here — e.g. a `UserRole.userID` straight out of Mongo.
 *
 * WHY THIS EXISTS IN THE .mjs AT ALL. The obvious argument against mirroring it
 * is that the TS version's whole point is the CanonicalUserID brand, and brands
 * are erased at runtime, so a plain-JS copy "means nothing". That argument is
 * half right and lands on the wrong conclusion. The function does two things:
 * it brands (compile-time, TS-only, genuinely meaningless here) and it RETURNS
 * null FOR ANYTHING FAILING THE SHAPE TEST, INCLUDING "" (runtime, and the
 * load-bearing half). A ""-keyed UserRole row — the I-8d red line — must enter
 * a migration script as ABSENT rather than as a usable key, and that hazard is
 * strictly WORSE in .mjs, where no type system is watching. rbac-doctor.mjs:115
 * already hand-rolls this exact shape test on a stored userID; this is the
 * shared name for it.
 *
 * So the export-surface mismatch is resolved by IMPLEMENTING, not by exempting.
 * Exempting would have meant teaching verify-identity-parity.mjs a per-symbol
 * allowlist — a hole in the one check that catches a function existing on one
 * side and not the other, punched open for a symbol that turns out to have real
 * runtime behaviour worth mirroring. Implementing keeps the surface check
 * absolute and costs eight lines.
 *
 * Carries NO provenance evidence — read isCanonicalResidentID's note. Never use
 * it to launder a caller-supplied id into a key.
 */
export function asStoredCanonicalUserID(id) {
  return isCanonicalResidentID(id) ? id : null;
}

/** @deprecated Alias — 05-verification.md §5 still names it this. */
export const isResidentEligible = isCanonicalResidentID;

export const AUTH_ERROR = { NOT_NUS_EMAIL: "NotNusEmail" };
